# Generated by Django 3.1.3 on 2020-11-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201130_1354'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_list',
        ),
    ]
